services:
  # --- 1. GATEWAY & MONITORING (DIŞA AÇIK KATMAN) ---
  dispatcher:
    build: ./dispatcher
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo-dispatcher:27017
      - AUTH_SERVICE_URL=http://auth-service:8001
      - USER_SERVICE_URL=http://user-service:8002
      - PRODUCT_SERVICE_URL=http://product-service:8003
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo-dispatcher
      - redis
    networks:
      - micro-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - micro-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - micro-network
    depends_on:
      - prometheus

  # --- 2. AUTH & SESSION (GÜVENLİK KATMANI) ---
  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - MONGO_URL=mongodb://mongo-auth:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo-auth
      - redis
    networks:
      - micro-network

  redis:
    image: redis:alpine
    container_name: redis-cache
    networks:
      - micro-network

  # --- 3. BUSINESS LOGIC (MİKROSERVİS KATMANI) ---
  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      - MONGO_URL=mongodb://mongo-product:27017
    depends_on:
      - mongo-product
    networks:
      - micro-network

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - MONGO_URL=mongodb://mongo-user:27017
    depends_on:
      - mongo-user
    networks:
      - micro-network

  # --- 4. DATA PERSISTENCE (VERİTABANI KATMANI - İZOLE) ---
  mongo-dispatcher:
    image: mongo:latest
    networks:
      - micro-network

  mongo-product:
    image: mongo:latest
    networks:
      - micro-network

  mongo-user:
    image: mongo:latest
    networks:
      - micro-network

  mongo-auth:
    image: mongo:latest
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge