services:
  # --- DISPATCHER (GATEWAY) BÖLÜMÜ ---
  dispatcher:
    build: ./dispatcher
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo-dispatcher:27017
      - USER_SERVICE_URL=http://user-service:8002
      - PRODUCT_SERVICE_URL=http://product-service:8003
    depends_on:
      - mongo-dispatcher
    networks:
      - micro-network

  # Dispatcher'ın İzole Veritabanı (Zorunluluk!)
  mongo-dispatcher:
    image: mongo:latest
    networks:
      - micro-network
    # Port dışarı açılmıyor -> Network Isolation

    # --- PRODUCT SERVICE BÖLÜMÜ ---
  product-service:
    build: ./product-service
    environment:
      - MONGO_URL=mongodb://mongo-product:27017
    depends_on:
      - mongo-product
    networks:
      - micro-network
    # Dışarı port açmıyoruz, sadece Dispatcher erişebilir

  mongo-product:
    image: mongo:latest
    networks:
      - micro-network

  # --- USER SERVICE BÖLÜMÜ ---
  user-service:
    build: ./user-service
    environment:
      - MONGO_URL=mongodb://mongo-user:27017
    depends_on:
      - mongo-user
    networks:
      - micro-network

  mongo-user:
    image: mongo:latest
    networks:
      - micro-network

  # --- AUTH SERVICE BÖLÜMÜ ---
  mongo-auth:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge

services:
  # --- YENİ: REDIS KATMANI  ---
  redis:
    image: redis:alpine
    container_name: redis-cache
    # Portu dışarı açmaya gerek yok, sadece iç ağda çalışsın
    networks:
      - micro-network

  # --- DISPATCHER GÜNCELLEMESİ ---
  dispatcher:
    build: ./dispatcher
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo-dispatcher:27017
      - USER_SERVICE_URL=http://user-service:8002
      - PRODUCT_SERVICE_URL=http://product-service:8003
      # Redis bağlantı bilgileri eklendi
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo-dispatcher
      - redis # Redis ayağa kalkmadan Dispatcher başlamasın
    networks:
      - micro-network

  # ... (Diğer servislerin (mongo-dispatcher, product-service vb.) aynı kalıyor) ...

  # --- AUTH SERVICE İÇİN GÜNCELLEME ---
  # Auth-service de Redis'e erişip token yazabilmeli
  auth-service:
    build: ./auth-service
    environment:
      - MONGO_URL=mongodb://mongo-auth:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo-auth
      - redis
    networks:
      - micro-network

# ... (Networks kısmı aynı kalıyor) ...