[pytest]
pythonpath = .
testpaths =
    shared/tests
    auth-service/auth_tests
    product-service/product_tests
    user-service/user_tests
    dispatcher/dispatcher_tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = strict
addopts = -v --tb=short
